name: Deploy

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yaml
  build:
    needs: checks
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.push.outputs.image_sha }}
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      REPO_NAME: devops-backend
      COMMIT_SHA: sha-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker build -t "$DOCKER_USER/$REPO_NAME:$COMMIT_SHA" -t "$DOCKER_USER/$REPO_NAME:latest" .

      - name: Login and Push to Docker Hub
        id: push
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "$DOCKER_USER" --password-stdin
          docker push -a "$DOCKER_USER/$REPO_NAME"
          echo "image_sha=$DOCKER_USER/$REPO_NAME:$COMMIT_SHA" >> $GITHUB_OUTPUT

  deploy:
    needs: [checks, build]
    runs-on: ubuntu-latest

    steps:
      - name: Деплой с использованием SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            sed -i "s|DOCKER_BACKEND_IMAGE=.*|DOCKER_BACKEND_IMAGE=${{ needs.build.outputs.image_sha }}|" .env
            docker compose up -d --no-deps backend

  notify:
    needs: [checks, build, deploy]
    if: always()
    uses: ./.github/workflows/notify.yaml
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

