name: Deploy

on:
  push:
    branches: [main]

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yaml
  build:
    needs: checks
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      REPO_NAME: devops-backend
      COMMIT_SHA: sha-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Images
        env:
          IMAGE_SHA: "$DOCKER_USER/$REPO_NAME:$COMMIT_SHA"
          IMAGE_LATEST: "$DOCKER_USER/$REPO_NAME:latest"
        run: |
          docker build -t "$IMAGE_SHA" -t "$IMAGE_LATEST" .

      - name: Login and Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "$DOCKER_USER" --password-stdin
          docker push -a "$DOCKER_USER/$REPO_NAME"
          echo "image_sha=$IMAGE_SHA" >> $GITHUB_OUTPUT

  deploy:
    needs: [checks, build]
    runs-on: ubuntu-latest

    steps:
      - name: Деплой с использованием SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            sed -i "s|DOCKER_BACKEND_IMAGE=.*|DOCKER_BACKEND_IMAGE=${{ needs.build.outputs.image_sha }}|" .env
            docker compose up --build -d --no-deps backend

  notify:
    needs: [checks, build, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Telegram
        run: |
          CHECKS="${{ needs.checks.result }}"
          DEPLOY_DOCKER="${{ needs.build.result }}"
          UPDATE_VPS="${{ needs.deploy.result }}"
          
          if [ "$CHECKS" != "success" ]; then
            TEXT="❌ Тесты упали%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          elif [ "$DEPLOY_DOCKER" != "success" ]; then
            TEXT="❌ Обновление образа в Docker Hub упало%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          elif [ "$UPDATE_VPS" != "success" ]; then
            TEXT="❌ Обновление VPS упало%0A${{ github.repository }} @ ${{ github.ref_name }}%0AСмотри: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            TEXT="✅ Деплой успешен%0A${{ github.repository }} | Автор: ${{github.actor}} @ ${{ github.ref_name }}"
          fi
          
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=$TEXT"
